version: 0.2

env:
  variables:
    AWS_REGION: eu-west-1
    STACK_NAME: serverless-api-pagamentos-dev
    SAM_ARTIFACT_BUCKET: sam-artifacts-pagamentos-nuno-20260624
    SAM_S3_PREFIX: serverless-api-pagamentos-dev
    ALLOWED_ORIGIN: https://main.d3at3wpexagb3r.amplifyapp.com
    SAM_CLI_TELEMETRY: 0
    COGNITO_DOMAIN_PREFIX: pagamentos-app-authenticator
    FRONTEND_URL: https://main.d3at3wpexagb3r.amplifyapp.com
    ALARM_NOTIFICATION_EMAIL: optic11051997@gmail.com

phases:
  install:
    commands:
      - echo "BUILD_SPEC_VERSION=deploy-sam-cors-v1"
      - java -version
      - mvn -version
      - sam --version

  pre_build:
    commands:
      - echo "Current directory:"
      - pwd
      - echo "Source files:"
      - ls -la
      - echo "Checking CORS in source template.yaml:"
      - grep -n "Cognito\|UserPool\|PagamentosHttpApi\|CorsConfiguration\|AllowedOrigin" template.yaml || true
      - sam validate --template-file template.yaml --region $AWS_REGION

  build:
    commands:
      - echo "Running clean SAM build..."
      - rm -rf .aws-sam
      - mvn -f .\PdfBoxLayer\pom.xml clean package
      - sam build
      - echo "Checking CORS in built SAM template:"
      - grep -n "Cognito\|UserPool\|PagamentosHttpApi\|CorsConfiguration\|AllowedOrigin" .aws-sam/build/template.yaml || true
      - echo "Deploying SAM stack..."
      - sam deploy --template-file .aws-sam/build/template.yaml --stack-name $STACK_NAME --s3-bucket $SAM_ARTIFACT_BUCKET --s3-prefix $SAM_S3_PREFIX --region $AWS_REGION --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides AllowedOrigin=$ALLOWED_ORIGIN FrontendUrl=$FRONTEND_URL CognitoDomainPrefix=$COGNITO_DOMAIN_PREFIX AlarmNotificationEmail=$ALARM_NOTIFICATION_EMAIL

  post_build:
    commands:
      - echo "CloudFormation stack status:"
      - aws cloudformation describe-stacks --stack-name $STACK_NAME --region $AWS_REGION --query "Stacks[0].StackStatus"
      - echo "CloudFormation outputs:"
      - aws cloudformation describe-stacks --stack-name $STACK_NAME --region $AWS_REGION --query "Stacks[0].Outputs"