# CodePipeline Configuration File
version: 0.2

env:
  variables:
    AWS_REGION: eu-west-1
    STACK_NAME: serverless-api-pagamentos-dev
    SAM_ARTIFACT_BUCKET: sam-artifacts-pagamentos-nuno-20260624
    SAM_S3_PREFIX: serverless-api-pagamentos-dev
    SAM_CLI_TELEMETRY: 0
    ALLOWED_ORIGIN: http://localhost:4200

phases:
  install:
    commands:
      - echo "BUILD_SPEC_VERSION=deploy-sam-v3"
      - echo "Checking Java, Maven and SAM versions..."
      - java -version
      - mvn -version
      - sam --version

  pre_build:
    commands:
      - echo "Current directory:"
      - pwd
      - echo "Files in source:"
      - ls -la
      - echo "Validating SAM template..."
      - sam validate --template-file template.yaml --region $AWS_REGION

  build:
    commands:
      - echo "Cleaning previous SAM build folder..."
      - rm -rf .aws-sam
      - echo "Building SAM application..."
      - sam build
      - echo "Deploying SAM application..."
      - sam deploy --stack-name $STACK_NAME --s3-bucket $SAM_ARTIFACT_BUCKET --s3-prefix $SAM_S3_PREFIX --region $AWS_REGION --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides AllowedOrigin=$ALLOWED_ORIGIN
  post_build:
    commands:
      - echo "Stack status:"
      - aws cloudformation describe-stacks --stack-name $STACK_NAME --region $AWS_REGION --query "Stacks[0].StackStatus"
      - echo "Stack outputs:"
      - aws cloudformation describe-stacks --stack-name $STACK_NAME --region $AWS_REGION --query "Stacks[0].Outputs"

artifacts:
  files:
    - packaged-template.yaml